### ISSUE TITLE
Deleting a Let Expression in Certain Places Can Cause a Crash

### ISSUE THREAD

**Issue by yottalogical** [hazelgrove/hazel#529] opened 2021-07-19 19:20 UTC
Here are a few examples of places that deleting a let expression causes a crash (this list is probably not exhaustive):

* As the bound expression of another let expression:
![Let Expression](https://user-images.githubusercontent.com/25121520/126213894-e5832122-c1a2-46e5-a69b-6716ae832304.png)
* As a function body:
![Function](https://user-images.githubusercontent.com/25121520/126213961-b5f4988e-c40b-4e3c-9893-133dbbff3b6b.png)
* As the expression of an injection:
![Injection](https://user-images.githubusercontent.com/25121520/126213995-b68392ad-fb0e-4973-8deb-efe1dc63d8a6.png)

The failure occurs here: https://github.com/hazelgrove/hazel/blob/8f196cc4720aaf8e41ca91e48c76fdf146ab0e73/src/hazelweb/model/Program.re#L156

This bug was noticed on commit [`8f196cc`](https://github.com/hazelgrove/hazel/commit/8f196cc4720aaf8e41ca91e48c76fdf146ab0e73), which was the location of the `dev` branch at the time this issue was filed.

**Comment by disconcision** [comment] 2021-07-19 19:40
See #278

**Comment by cyrus-** [comment] 2021-07-21 16:23
Thanks for the report! Closing as a duplicate of #278. Should be fixed in a future commit.

**Closed as completed** 2022-01-20 18:22 UTC
Labels: bug, duplicate
