### ISSUE TITLE
missing indentation within case rules

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#743] opened 2022-08-28 03:40 UTC
![Screenshot from 2022-08-27 23-40-23](https://user-images.githubusercontent.com/280638/187056324-151e5835-5eb6-4e84-8135-9ee71141f588.png)

**Comment by disconcision** [comment] 2023-08-22 02:19
closed as dupe of #882 (closing older one as newer is more comprehensive)

**Closed as completed by disconcision** 2023-08-22 02:19 UTC
Labels: bug
